version: '3.5'

services:
    frontend:
        build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
        ports: 
          - 3000:3000
    backend:
        build: https://github.com/docker-hy/ml-kurkkumopo-backend.git 
        ports:
          - 5000:5000
        volumes:
          - model:/src/model
        depends_on:
          - training
    training:
        build: https://github.com/docker-hy/ml-kurkkumopo-training.git
        volumes:
          - model:/src/model
          - imgs:/src/imgs

volumes:
    model:
    imgs:
