version: '3.5' 

services: 
    frontend:  
      build: frontend/.

    backend:
      build: backend/.
      environment:
        - REDIS_HOST=redis_addition
        - POSTGRES_USER=db_user
        - POSTGRES_PASSWORD=example
        - POSTGRES_DB=db

      depends_on:
        - db
        - redis_addition

    redis_addition:
      image: redis
      volumes: 
       - ./redis:/data

    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: db_user
        POSTGRES_PASSWORD: example
      volumes:
        - ./database:/var/lib/postgresql/data

    proxy:
      image: nginx
      ports:
       - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - backend
        - frontend
