version: '3.8'

services:
    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=example
      volumes:
        - ./database:/var/lib/postgresql/data

    frontend:
      build: frontend/.
      ports:
        - 5000:5000

    backend:
      build: backend/.
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=example
        - POSTGRES_HOST=db
      depends_on:
        - db
        - redis

    redis:
      image: redis
      volumes:
        - ./redis:/data
