version: '3.5' 

services: 
    frontend:  
      build: frontend/.
#      ports:
#        - 5000:5000

    backend:
      build: backend/.
      ports:
        - 8000:8000
      environment:
        - REDIS=redis_addition
        - DB_USERNAME=db_user
        - DB_PASSWORD=example
        - DB_HOST=db
      depends_on:
        - db

    redis_addition:
      image: redis

    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: db_user
        POSTGRES_PASSWORD: example

    proxy:
      image: jwilder/nginx-proxy
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
