version: '3.8'

services:
    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: example

    frontend:
      build: frontend/.
      ports:
        - 5000:5000

    backend:
      build: backend/.
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=example
      depends_on:
        - db

    redis:
      image: redis
